### PR TITLE
Upgrade minimist to version 1.2.8

### PR DESCRIPTION
**Pull request by gushil**

### CODE REVIEW

**Comment by MartijnR** [comment]
Hi Agus!

This fork is not in use, I believe. It's not up to date and I don't remember why it was created.

**Comment by svadla-oc** [comment]
@MartijnR if it's not in use, do you recommend deleting this fork?

**Comment by MartijnR** [comment]
yes, I think so but actually just noticed the readme of this fork. It appears that this was used in the past. It describes when this repo can be deleted.

**Comment by svadla-oc** [comment]
thanks @MartijnR. It looks like we still need to keep this fork as an older version of enketo-express-oc is being used in prod.

**Review by svadla-oc — APPROVED** [review]

**Pull request merged**
